version: '2'
services:
    loja-app:
        image: loja
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://loja-postgresql:5432/loja
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=loja-elasticsearch:9300
        ports:
            - 8080:8080
    loja-postgresql:
        extends:
            file: postgresql.yml
            service: loja-postgresql
    loja-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: loja-elasticsearch
