version: '2'
services:
    loja-postgresql:
        container_name: loja-postgresql
        image: postgres:9.5.1
        # volumes:
        #     - ~/volumes/jhipster/loja/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=loja
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
